nacos:
  host: ''
  port: 0
  namespace: ''
  user: ''
  password: ''
  dataid: ''
  group: ''
  cluster: ""
  open: false
service:
  name: ''
  metadata:
  host: ''
  port: 0
  group: ''
  cluster: ''
  checkAddr: '/check'
  namespace: ''
consul:
  id: ""
  host: ''
jaeger:
  host: ''
  port: ""
mysql:
  host: ''
  port: ""
  user: ''
  name: ''
  password: ''
  prefix: ''
redis:
  host: ''
  port: ""
  password: ''
  db: 0
jwt:
  key: ''
  expires:
kafka:
  address:
    - 192.168.9.100:9093
    - 192.168.9.100:9092
  username: ""
  password: ""
logs:
  filename: ""
oss:
  endpoint: ''
  bucket: ''
  id: ''
  secret: ''
sls:
  name: ""
  id: ""
  secret: ""
  host: ""
  storeName: ""
master:
  jwt:
    privateKey:
    publicKey: ""
    expires:
  host: ""
  auth: ""