nacos:
  host: '192.168.9.100'
  port: 8848
  namespace: ''
  user: 'nacos'
  password: 'nacos'
  dataid: 'airmart_nft_admin-dev.yaml'
  group: 'dev'
  cluster: "airmart_nft_admin"
  open: false
service:
  name: 'airmart_nft_admin'
  metadata:
  host: '192.168.9.100'
  port: 9050
  group: 'dev'
  cluster: 'airmart_nft_admin'
  checkAddr: '/check'
  namespace: ''
consul:
  id: "026b2d83-88ff-462a-b21c-9db9118bccef"
  host: '192.168.9.100:8500'
jaeger:
  host: '192.168.9.100'
  port: "6831"
mysql:
  host: '192.168.9.100'
  port: "3306"
  user: 'root'
  name: 'airmart_nft'
  password: '123456'
  prefix: 'nft_'
redis:
  host: '192.168.9.100'
  port: "6379"
  password: ''
  db: 2
jwt:
  key: 'abcd'
  expires:
kafka:
  address:
    - 192.168.9.100:9093
    - 192.168.9.100:9092
  username: "adminscram"
  password: "admin-secret"
logs:
  filename: "./logs/airmart_nft_admin.log"
oss:
  endpoint: 'https://oss-cn-hangzhou.aliyuncs.com'
  bucket: 'airmart3'
  id: 'LTAI5tCA6XcYCjdzS1NV14gR'
  secret: 'cfeppFmU50EsNyaU7G7nuFka2lPtAh'
sls:
  name: "airmart-combo-box"
  id: "LTAI5t8qDE4aCcQnNWWYe5eT"
  secret: "7yh9OvbRdLexFYBSwRQITrrIxZiqVN"
  host: "cn-shanghai.log.aliyuncs.com"
  storeName: "admin"
master:
  jwt:
    privateKey:
    publicKey: "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDV7lDiyoqkfaOvx0yY9RvoxtV3\nbfAACAzDLjvyasVF3MFcdRIAx3NTXZoylxxkD8Thd7k3bOwTFONOf4zi3iUkSKOZ\ny2Hhtbpvh8xWQC1P3ERnAyJA8wpZvwGL20mXpmdPe8QdF6Y2q1BTb9OyqfSfNHLA\nXBbylLYcGoTMjqSF6wIDAQAB\n-----END PUBLIC KEY-----"
    expires:
  host: "https://api-airmart-sit.66skins.co"
  auth: "Bearer hKEEFzt1rGfKDXTx"